services:
  mediamtx:
    image: bluenviron/mediamtx:1-ffmpeg
    container_name: mediamtx
    restart: unless-stopped
    ports:
      - "8554:8554"
      - "8554:8554/udp"
      - "8080:8080"
      - "8888:8888"
      - "8889:8889"
      - "8189:8189/udp"
    volumes:
      - ./mediamtx/mediamtx.yml:/mediamtx.yml
      - ./recordings:/recordings
  
  db:
    image: postgres:latest
    container_name: postgreSQL
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORTS}:5432"