[app]
OCR_DEBUG = false
OCR_WORKERS = 1
OCR_CONF_THRESHOLD = 0.45
OCR_BRIGHTNESS_LOW = 40
OCR_BRIGHTNESS_HIGH = 220
ROI_RATIO = 0.15
INACTIVE_FRAMES = 40

[minio]
ENDPOINT = "minio:9000"
ACCESS_KEY = "minioadmin"
SECRET_KEY = "minioadmin"
BUCKET = "plates"
SECURE = false